version: '2.1'

services:
  selenium:
    extends:
      file: docker-compose.base.yml
      service: selenium
    depends_on:
      - chrome
      - firefox

  chrome:
    extends:
      file: docker-compose.base.yml
      service: chrome

  firefox:
    extends:
      file: docker-compose.base.yml
      service: firefox
