version: '2.1'

services:
  selenium:
    image: selenium/hub:3.141.59-neon
    ports:
      - "${HUB_PORT:-4444}:4444"
    devices:
      # Try to prevent Selenium from blocking when creating sessions due to
      # limited entropy.
      - /dev/urandom:/dev/random
    volumes:
      - /dev/shm:/dev/shm

  hub:
    extends:
      service: selenium
    depends_on:
      - chrome
      - firefox

  chrome:
    image: selenium/node-chrome:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT=4444
      - HUB_HOST=hub

  firefox:
    image: selenium/node-firefox:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT=4444
      - HUB_HOST=hub

  debug_hub:
    extends:
      service: selenium
    environment:
      - SE_OPTS=-debug
      - GRID_TIMEOUT=0
      - BROWSER_TIMEOUT=0
    depends_on:
      - debug_chrome
      - debug_firefox

  debug_chrome:
    image: "selenium/node-chrome-debug:3.141.59-neon"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT=4444
      - HUB_HOST=debug_hub
      - SE_OPTS=-debug
    ports:
      - '5900:5900' # VNC

  debug_firefox:
    image: "selenium/node-firefox-debug:3.141.59-neon"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT=4444
      - HUB_HOST=debug_hub
      - SE_OPTS=-debug
    ports:
      - '5901:5900' # VNC

networks:
  default:
    # Explicitly name the default network so that others can join it.
    name: tdd-buffet
