version: '2.1'

services:
  selenium:
    extends:
      file: docker-compose.base.yml
      service: selenium
    environment:
      - SE_OPTS=-debug
      - GRID_TIMEOUT=0
      - BROWSER_TIMEOUT=0
    depends_on:
      - debug_chrome
      - debug_firefox

  debug_chrome:
    extends:
      file: docker-compose.base.yml
      service: debug_chrome
    ports:
      - '5900:5900' # VNC

  debug_firefox:
    extends:
      file: docker-compose.base.yml
      service: debug_firefox
    ports:
      - '5901:5900' # VNC
